
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vBox;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Label Texto;

	private global::Gtk.Button buttonsacarbola;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vBox = new global::Gtk.VBox();
		this.vBox.Name = "vBox";
		this.vBox.Spacing = 6;
		// Container child vBox.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.Texto = new global::Gtk.Label();
		this.Texto.Name = "Texto";
		this.Texto.LabelProp = global::Mono.Unix.Catalog.GetString("BINGO");
		this.hbox1.Add(this.Texto);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.Texto]));
		w1.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.buttonsacarbola = new global::Gtk.Button();
		this.buttonsacarbola.CanFocus = true;
		this.buttonsacarbola.Name = "buttonsacarbola";
		this.buttonsacarbola.UseUnderline = true;
		this.buttonsacarbola.Label = global::Mono.Unix.Catalog.GetString("Sacar bola");
		this.hbox1.Add(this.buttonsacarbola);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.buttonsacarbola]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		this.vBox.Add(this.hbox1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vBox[this.hbox1]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		this.Add(this.vBox);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
	}
}
