
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox3;

	private global::Gtk.HBox hbox8;

	private global::Gtk.Label Ctitulo;

	private global::Gtk.Button Csalir;

	private global::Gtk.Entry Pantalla;

	private global::Gtk.HBox hbox7;

	private global::Gtk.Button Cvaciar;

	private global::Gtk.Button Ccancelar;

	private global::Gtk.HBox hbox6;

	private global::Gtk.Button Csiete;

	private global::Gtk.Button Cocho;

	private global::Gtk.Button Cnueve;

	private global::Gtk.Button Cdividir;

	private global::Gtk.HBox hbox5;

	private global::Gtk.Button Ccuatro;

	private global::Gtk.Button Ccinco;

	private global::Gtk.Button Cseis;

	private global::Gtk.Button Cmultiplicar;

	private global::Gtk.HBox hbox4;

	private global::Gtk.Button Cuno;

	private global::Gtk.Button Cdos;

	private global::Gtk.Button Ctres;

	private global::Gtk.Button Cmenos;

	private global::Gtk.HBox hbox3;

	private global::Gtk.Button Ccoma;

	private global::Gtk.Button Ccero;

	private global::Gtk.Button Cigual;

	private global::Gtk.Button Cmas;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(9));
		this.Resizable = false;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox3 = new global::Gtk.VBox();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox8 = new global::Gtk.HBox();
		this.hbox8.Name = "hbox8";
		this.hbox8.Spacing = 6;
		// Container child hbox8.Gtk.Box+BoxChild
		this.Ctitulo = new global::Gtk.Label();
		this.Ctitulo.Name = "Ctitulo";
		this.Ctitulo.LabelProp = global::Mono.Unix.Catalog.GetString("Calculadora v.1.0");
		this.hbox8.Add(this.Ctitulo);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.Ctitulo]));
		w1.Position = 0;
		// Container child hbox8.Gtk.Box+BoxChild
		this.Csalir = new global::Gtk.Button();
		this.Csalir.CanFocus = true;
		this.Csalir.Name = "Csalir";
		this.Csalir.UseUnderline = true;
		this.Csalir.Label = global::Mono.Unix.Catalog.GetString("Salir");
		this.hbox8.Add(this.Csalir);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.Csalir]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		this.vbox3.Add(this.hbox8);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox8]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.Pantalla = new global::Gtk.Entry();
		this.Pantalla.CanFocus = true;
		this.Pantalla.Name = "Pantalla";
		this.Pantalla.IsEditable = false;
		this.Pantalla.InvisibleChar = '•';
		this.vbox3.Add(this.Pantalla);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.Pantalla]));
		w4.Position = 1;
		w4.Expand = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.Cvaciar = new global::Gtk.Button();
		this.Cvaciar.CanFocus = true;
		this.Cvaciar.Name = "Cvaciar";
		this.Cvaciar.UseUnderline = true;
		this.Cvaciar.Label = global::Mono.Unix.Catalog.GetString("Vaciar");
		this.hbox7.Add(this.Cvaciar);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.Cvaciar]));
		w5.Position = 0;
		// Container child hbox7.Gtk.Box+BoxChild
		this.Ccancelar = new global::Gtk.Button();
		this.Ccancelar.WidthRequest = 50;
		this.Ccancelar.HeightRequest = 50;
		this.Ccancelar.Name = "Ccancelar";
		this.Ccancelar.UseUnderline = true;
		this.Ccancelar.Label = "C";
		this.hbox7.Add(this.Ccancelar);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.Ccancelar]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		this.vbox3.Add(this.hbox7);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox7]));
		w7.Position = 2;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.Csiete = new global::Gtk.Button();
		this.Csiete.WidthRequest = 50;
		this.Csiete.HeightRequest = 50;
		this.Csiete.CanFocus = true;
		this.Csiete.Name = "Csiete";
		this.Csiete.UseUnderline = true;
		this.Csiete.Label = global::Mono.Unix.Catalog.GetString("7");
		this.hbox6.Add(this.Csiete);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.Csiete]));
		w8.Position = 0;
		// Container child hbox6.Gtk.Box+BoxChild
		this.Cocho = new global::Gtk.Button();
		this.Cocho.WidthRequest = 50;
		this.Cocho.HeightRequest = 50;
		this.Cocho.CanFocus = true;
		this.Cocho.Name = "Cocho";
		this.Cocho.UseUnderline = true;
		this.Cocho.Label = global::Mono.Unix.Catalog.GetString("8");
		this.hbox6.Add(this.Cocho);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.Cocho]));
		w9.Position = 1;
		// Container child hbox6.Gtk.Box+BoxChild
		this.Cnueve = new global::Gtk.Button();
		this.Cnueve.WidthRequest = 50;
		this.Cnueve.HeightRequest = 50;
		this.Cnueve.CanFocus = true;
		this.Cnueve.Name = "Cnueve";
		this.Cnueve.UseUnderline = true;
		this.Cnueve.Label = global::Mono.Unix.Catalog.GetString("9");
		this.hbox6.Add(this.Cnueve);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.Cnueve]));
		w10.Position = 2;
		// Container child hbox6.Gtk.Box+BoxChild
		this.Cdividir = new global::Gtk.Button();
		this.Cdividir.WidthRequest = 50;
		this.Cdividir.HeightRequest = 50;
		this.Cdividir.CanFocus = true;
		this.Cdividir.Name = "Cdividir";
		this.Cdividir.UseUnderline = true;
		this.Cdividir.Label = global::Mono.Unix.Catalog.GetString("/");
		this.hbox6.Add(this.Cdividir);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.Cdividir]));
		w11.Position = 3;
		this.vbox3.Add(this.hbox6);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox6]));
		w12.Position = 3;
		w12.Expand = false;
		w12.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.Ccuatro = new global::Gtk.Button();
		this.Ccuatro.WidthRequest = 50;
		this.Ccuatro.HeightRequest = 50;
		this.Ccuatro.CanFocus = true;
		this.Ccuatro.Name = "Ccuatro";
		this.Ccuatro.UseUnderline = true;
		this.Ccuatro.Label = global::Mono.Unix.Catalog.GetString("4");
		this.hbox5.Add(this.Ccuatro);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.Ccuatro]));
		w13.Position = 0;
		// Container child hbox5.Gtk.Box+BoxChild
		this.Ccinco = new global::Gtk.Button();
		this.Ccinco.WidthRequest = 50;
		this.Ccinco.HeightRequest = 50;
		this.Ccinco.CanFocus = true;
		this.Ccinco.Name = "Ccinco";
		this.Ccinco.UseUnderline = true;
		this.Ccinco.Label = global::Mono.Unix.Catalog.GetString("5");
		this.hbox5.Add(this.Ccinco);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.Ccinco]));
		w14.Position = 1;
		// Container child hbox5.Gtk.Box+BoxChild
		this.Cseis = new global::Gtk.Button();
		this.Cseis.WidthRequest = 50;
		this.Cseis.HeightRequest = 50;
		this.Cseis.CanFocus = true;
		this.Cseis.Name = "Cseis";
		this.Cseis.UseUnderline = true;
		this.Cseis.Label = global::Mono.Unix.Catalog.GetString("6");
		this.hbox5.Add(this.Cseis);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.Cseis]));
		w15.Position = 2;
		// Container child hbox5.Gtk.Box+BoxChild
		this.Cmultiplicar = new global::Gtk.Button();
		this.Cmultiplicar.WidthRequest = 50;
		this.Cmultiplicar.HeightRequest = 50;
		this.Cmultiplicar.CanFocus = true;
		this.Cmultiplicar.Name = "Cmultiplicar";
		this.Cmultiplicar.UseUnderline = true;
		this.Cmultiplicar.Label = global::Mono.Unix.Catalog.GetString("*");
		this.hbox5.Add(this.Cmultiplicar);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.Cmultiplicar]));
		w16.Position = 3;
		this.vbox3.Add(this.hbox5);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox5]));
		w17.Position = 4;
		w17.Expand = false;
		w17.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.Cuno = new global::Gtk.Button();
		this.Cuno.WidthRequest = 50;
		this.Cuno.HeightRequest = 50;
		this.Cuno.CanFocus = true;
		this.Cuno.Name = "Cuno";
		this.Cuno.UseUnderline = true;
		this.Cuno.Label = global::Mono.Unix.Catalog.GetString("1");
		this.hbox4.Add(this.Cuno);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.Cuno]));
		w18.Position = 0;
		// Container child hbox4.Gtk.Box+BoxChild
		this.Cdos = new global::Gtk.Button();
		this.Cdos.WidthRequest = 50;
		this.Cdos.HeightRequest = 50;
		this.Cdos.CanFocus = true;
		this.Cdos.Name = "Cdos";
		this.Cdos.UseUnderline = true;
		this.Cdos.Label = global::Mono.Unix.Catalog.GetString("2");
		this.hbox4.Add(this.Cdos);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.Cdos]));
		w19.Position = 1;
		// Container child hbox4.Gtk.Box+BoxChild
		this.Ctres = new global::Gtk.Button();
		this.Ctres.WidthRequest = 50;
		this.Ctres.HeightRequest = 50;
		this.Ctres.CanFocus = true;
		this.Ctres.Name = "Ctres";
		this.Ctres.UseUnderline = true;
		this.Ctres.Label = global::Mono.Unix.Catalog.GetString("3");
		this.hbox4.Add(this.Ctres);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.Ctres]));
		w20.Position = 2;
		// Container child hbox4.Gtk.Box+BoxChild
		this.Cmenos = new global::Gtk.Button();
		this.Cmenos.WidthRequest = 50;
		this.Cmenos.HeightRequest = 50;
		this.Cmenos.CanFocus = true;
		this.Cmenos.Name = "Cmenos";
		this.Cmenos.UseUnderline = true;
		this.Cmenos.Label = global::Mono.Unix.Catalog.GetString("-");
		this.hbox4.Add(this.Cmenos);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.Cmenos]));
		w21.Position = 3;
		this.vbox3.Add(this.hbox4);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox4]));
		w22.Position = 5;
		w22.Expand = false;
		w22.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.Ccoma = new global::Gtk.Button();
		this.Ccoma.WidthRequest = 50;
		this.Ccoma.HeightRequest = 50;
		this.Ccoma.CanFocus = true;
		this.Ccoma.Name = "Ccoma";
		this.Ccoma.UseUnderline = true;
		this.Ccoma.Label = global::Mono.Unix.Catalog.GetString(".");
		this.hbox3.Add(this.Ccoma);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.Ccoma]));
		w23.Position = 0;
		// Container child hbox3.Gtk.Box+BoxChild
		this.Ccero = new global::Gtk.Button();
		this.Ccero.WidthRequest = 50;
		this.Ccero.HeightRequest = 50;
		this.Ccero.CanFocus = true;
		this.Ccero.Name = "Ccero";
		this.Ccero.UseUnderline = true;
		this.Ccero.Label = global::Mono.Unix.Catalog.GetString("0");
		this.hbox3.Add(this.Ccero);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.Ccero]));
		w24.Position = 1;
		// Container child hbox3.Gtk.Box+BoxChild
		this.Cigual = new global::Gtk.Button();
		this.Cigual.WidthRequest = 50;
		this.Cigual.HeightRequest = 50;
		this.Cigual.CanFocus = true;
		this.Cigual.Name = "Cigual";
		this.Cigual.UseUnderline = true;
		this.Cigual.Label = global::Mono.Unix.Catalog.GetString("=");
		this.hbox3.Add(this.Cigual);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.Cigual]));
		w25.Position = 2;
		// Container child hbox3.Gtk.Box+BoxChild
		this.Cmas = new global::Gtk.Button();
		this.Cmas.WidthRequest = 50;
		this.Cmas.HeightRequest = 50;
		this.Cmas.CanFocus = true;
		this.Cmas.Name = "Cmas";
		this.Cmas.UseUnderline = true;
		this.Cmas.Label = global::Mono.Unix.Catalog.GetString("+");
		this.hbox3.Add(this.Cmas);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.Cmas]));
		w26.Position = 3;
		this.vbox3.Add(this.hbox3);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox3]));
		w27.Position = 6;
		w27.Expand = false;
		w27.Fill = false;
		this.Add(this.vbox3);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 244;
		this.DefaultHeight = 360;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.Csalir.Clicked += new global::System.EventHandler(this.OnCsalirClicked);
		this.Cvaciar.Clicked += new global::System.EventHandler(this.OnCvaciarClicked);
		this.Ccancelar.Clicked += new global::System.EventHandler(this.OnCcancelarClicked);
		this.Csiete.Clicked += new global::System.EventHandler(this.OnCsieteClicked);
		this.Cocho.Clicked += new global::System.EventHandler(this.OnCochoClicked);
		this.Cnueve.Clicked += new global::System.EventHandler(this.OnCnueveClicked);
		this.Cdividir.Clicked += new global::System.EventHandler(this.OnCdividirClicked);
		this.Ccuatro.Clicked += new global::System.EventHandler(this.OnCcuatroClicked);
		this.Ccinco.Clicked += new global::System.EventHandler(this.OnCcincoClicked);
		this.Cseis.Clicked += new global::System.EventHandler(this.OnCseisClicked);
		this.Cmultiplicar.Clicked += new global::System.EventHandler(this.OnCmultiplicarClicked);
		this.Cuno.Clicked += new global::System.EventHandler(this.OnCunoClicked);
		this.Cdos.Clicked += new global::System.EventHandler(this.OnCdosClicked);
		this.Ctres.Clicked += new global::System.EventHandler(this.OnCtresClicked);
		this.Cmenos.Clicked += new global::System.EventHandler(this.OnCmenosClicked);
		this.Ccoma.Clicked += new global::System.EventHandler(this.OnCcomaClicked);
		this.Ccero.Clicked += new global::System.EventHandler(this.OnCceroClicked);
		this.Cigual.Clicked += new global::System.EventHandler(this.OnCigualClicked);
		this.Cmas.Clicked += new global::System.EventHandler(this.OnCmasClicked);
	}
}
